# 이것은 문서입니다

## 이것은 작은 문서입니다
- 이것은 불렛
 - 다음단계
> 이것은 들여쓰기

여러줄은   
이렇게 나눈다

In [45]:
x = 3
a = 0.1
b = 'Hello'
c = True
d = False

In [46]:
print(x+c+d)
print(x*3)

4
9


In [47]:
# [ 사용되는 경우 : 리스트, 인덱싱]
x = [1,2,3,4,5]

In [48]:
type(x)

list

In [49]:
x*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [50]:
[i*3 for i in x]

[3, 6, 9, 12, 15]

In [51]:
[i*i for i in x]

[1, 4, 9, 16, 25]

In [53]:
y = range(10)
y

range(0, 10)

In [54]:
[i*i for i in y]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [65]:
y=range(1,10,2)
y

range(1, 10, 2)

In [61]:
for i in y:
    print (i*2)

2
6
10
14
18


In [64]:
import numpy as np
y = np.arange(1,2,0.2)
y.shape

(5,)

In [72]:
y = np.arange(12);
y = y.reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
y.shape

(3, 4)

In [77]:
y= y.reshape(2,2,3)
y.shape

(2, 2, 3)

In [78]:
y.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [79]:
y.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [81]:
y.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [82]:
# 튜플
a,b = 4,5

In [83]:
a

4

In [84]:
5

5

In [103]:
x = [4,3,6,7,1]

In [104]:
x[2]

6

In [105]:
x[2]=1000
x[2]

1000

In [106]:
x = (4,3,6,7,1)
x[2]

6

In [107]:
x[2] = 1000

TypeError: 'tuple' object does not support item assignment

In [108]:
# 딕셔너리
x = {'name':'kim', 'age' : 21, 'sex':'Male'}
x.keys()

dict_keys(['name', 'age', 'sex'])

In [109]:
x.values()

dict_values(['kim', 21, 'Male'])

In [115]:
import pandas as pd
pd.DataFrame(x)

ValueError: If using all scalar values, you must pass an index

In [116]:
# 딕셔너리
x = {'name':['kim'], 'age' : [21], 'sex':['Male']}
x.keys()

dict_keys(['name', 'age', 'sex'])

In [117]:
pd.DataFrame(x)

name  age   sex
0  kim   21  Male